-- MySQL Script generated by MySQL Workbench
-- 03/04/15 10:48:39
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fullbright_assistance_program
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullbright_assistance_program` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fullbright_assistance_program` ;

-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`adviser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`adviser` (
  `adviser_id` INT(11) NOT NULL AUTO_INCREMENT,
  `adviser_fname` VARCHAR(45) NOT NULL,
  `adviser_lname` VARCHAR(45) NOT NULL,
  `adviser_address` VARCHAR(45) NOT NULL,
  `adviser_contact` INT(11) NOT NULL,
  `adviser_uname` VARCHAR(45) NOT NULL,
  `adviser_password` VARCHAR(45) NOT NULL,
  `adviser_emailadd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`adviser_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`parent` (
  `parent_id` INT(11) NOT NULL AUTO_INCREMENT,
  `parent_fname` VARCHAR(45) NOT NULL,
  `parent_lname` VARCHAR(45) NOT NULL,
  `parent_address` VARCHAR(45) NOT NULL,
  `parent_contact` VARCHAR(45) NOT NULL,
  `parent_remarks` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`parent_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`subject_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`subject_teacher` (
  `teacher_id` INT(11) NOT NULL AUTO_INCREMENT,
  `teacher_fname` VARCHAR(45) NOT NULL,
  `teacher_lname` VARCHAR(45) NOT NULL,
  `teacher_address` VARCHAR(45) NOT NULL,
  `teacher_desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`student` (
  `student_id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_fname` VARCHAR(45) NOT NULL,
  `student_lname` VARCHAR(45) NOT NULL,
  `student_section` VARCHAR(45) NOT NULL,
  `student_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`grades` (
  `grade_id` INT(11) NOT NULL AUTO_INCREMENT,
  `grade_desc` VARCHAR(45) NOT NULL,
  `adviser_adviser_id` INT(11) NOT NULL,
  `parent_parent_id` INT(11) NOT NULL,
  `subject_teacher_teacher_id` INT(11) NOT NULL,
  `student_student_id` INT(11) NOT NULL,
  PRIMARY KEY (`grade_id`),
  INDEX `fk_grades_adviser_idx` (`adviser_adviser_id` ASC),
  INDEX `fk_grades_parent1_idx` (`parent_parent_id` ASC),
  INDEX `fk_grades_subject_teacher1_idx` (`subject_teacher_teacher_id` ASC),
  INDEX `fk_grades_student1_idx` (`student_student_id` ASC),
  CONSTRAINT `fk_grades_adviser`
    FOREIGN KEY (`adviser_adviser_id`)
    REFERENCES `fullbright_assistance_program`.`adviser` (`adviser_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_parent1`
    FOREIGN KEY (`parent_parent_id`)
    REFERENCES `fullbright_assistance_program`.`parent` (`parent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_subject_teacher1`
    FOREIGN KEY (`subject_teacher_teacher_id`)
    REFERENCES `fullbright_assistance_program`.`subject_teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `fullbright_assistance_program`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`subjects` (
  `subject_id` INT(11) NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(45) NOT NULL,
  `subject_desc` VARCHAR(45) NOT NULL,
  `subject_remarks` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`subject_teacher_has_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`subject_teacher_has_subjects` (
  `subject_teacher_teacher_id` INT(11) NOT NULL,
  `subjects_subject_id` INT(11) NOT NULL,
  PRIMARY KEY (`subject_teacher_teacher_id`, `subjects_subject_id`),
  INDEX `fk_subject_teacher_has_subjects_subjects1_idx` (`subjects_subject_id` ASC),
  INDEX `fk_subject_teacher_has_subjects_subject_teacher1_idx` (`subject_teacher_teacher_id` ASC),
  CONSTRAINT `fk_subject_teacher_has_subjects_subject_teacher1`
    FOREIGN KEY (`subject_teacher_teacher_id`)
    REFERENCES `fullbright_assistance_program`.`subject_teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_teacher_has_subjects_subjects1`
    FOREIGN KEY (`subjects_subject_id`)
    REFERENCES `fullbright_assistance_program`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`student_has_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`student_has_subjects` (
  `student_student_id` INT(11) NOT NULL,
  `subjects_subject_id` INT(11) NOT NULL,
  PRIMARY KEY (`student_student_id`, `subjects_subject_id`),
  INDEX `fk_student_has_subjects_subjects1_idx` (`subjects_subject_id` ASC),
  INDEX `fk_student_has_subjects_student1_idx` (`student_student_id` ASC),
  CONSTRAINT `fk_student_has_subjects_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `fullbright_assistance_program`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_subjects_subjects1`
    FOREIGN KEY (`subjects_subject_id`)
    REFERENCES `fullbright_assistance_program`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
