-- MySQL Script generated by MySQL Workbench
-- 03/06/15 01:13:10
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fullbright_assistance_program
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullbright_assistance_program` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fullbright_assistance_program` ;

-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`adviser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`adviser` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `adviser_fname` VARCHAR(45) NOT NULL,
  `adviser_lname` VARCHAR(45) NOT NULL,
  `adviser_address` VARCHAR(45) NOT NULL,
  `adviser_contact` INT(11) NOT NULL,
  `adviser_uname` VARCHAR(45) NOT NULL,
  `adviser_password` VARCHAR(45) NOT NULL,
  `adviser_emailadd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`grades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `grade_desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`parents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`parents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `parents_fname` VARCHAR(45) NOT NULL,
  `parents_lname` VARCHAR(45) NOT NULL,
  `parents_address` VARCHAR(45) NOT NULL,
  `parents_contact` VARCHAR(45) NOT NULL,
  `parents_remarks` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`student` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_fname` VARCHAR(45) NOT NULL,
  `student_lname` VARCHAR(45) NOT NULL,
  `student_section` VARCHAR(45) NOT NULL,
  `student_address` VARCHAR(45) NOT NULL,
  `parents_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_parents1_idx` (`parents_id` ASC),
  CONSTRAINT `fk_student_parents1`
    FOREIGN KEY (`parents_id`)
    REFERENCES `fullbright_assistance_program`.`parents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fullbright_assistance_program`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullbright_assistance_program`.`subjects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(45) NOT NULL,
  `subject_desc` VARCHAR(45) NOT NULL,
  `subject_remarks` VARCHAR(45) NOT NULL,
  `grades_id` INT(11) NOT NULL,
  `adviser_id` INT(11) NOT NULL,
  `student_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `grades_id`, `adviser_id`, `student_id`),
  INDEX `fk_subjects_grades1_idx` (`grades_id` ASC),
  INDEX `fk_subjects_adviser1_idx` (`adviser_id` ASC),
  INDEX `fk_subjects_student1_idx` (`student_id` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
